### ISSUE TITLE
`cubify` returns weird shape, or I use it worng

### ISSUE THREAD

**Issue by dmitrijs-balcers** [colinmeinke/points#10]
Hello @colinmeinke, first of all thank you for making this repository public.

I'm have a need to transform an `arc` to `cubic bezier` in my svg. And for that I'm trying to use `cubify` method. But for some reason it returns me wrong result or I'm doing something wrong. I hope you may help me.

So to be more specific. I've tried to do the following
```
var mapToCubicString = (c) => `C${cutN(c.x)} ${cutN(c.y)} ${cutN(c.curve.x1)} ${cutN(c.curve.y1)} ${cutN(c.curve.x2)} ${cutN(c.curve.y2)}`;
var cubic = _.tail(points.cubify([
            { x: 50, y: 30, moveTo: true },
            { x: 50, y: 70, curve: { type: 'arc', rx: 20, ry: 20, sweepFlag: 1 } },
            { x: 50, y: 30, curve: { type: 'arc', rx: 20, ry: 20, sweepFlag: 1 } },
        ]
    )).map(mapToCubicString);
```

`mapToCubicString` will be equal to:
```
[ 
  'C70 50 61.046 30 70 38.954',
  'C50 70 70 61.046 61.046 70',
  'C30 50 38.954 70 30 61.046',
  'C50 30 30 38.954 38.954 30' 
]
```

after some manipulations we will get such svg:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 832.97 218">
    <defs>
        <style>
            .cls-1{opacity:0.7;}.cls-2{fill:#fff;}
        </style>
    </defs>
    <path stroke="#00f" class="cls-2 bet_8" d="M62.25 134.49C70 50 61.046 30 70 38.954C50 70 70 61.046 61.046 70C30 50 38.954 70 30 61.046C50 30 30 38.954 38.954 30" />
</svg>
```

which will lead to the following image:
<img width="157" alt="screen shot 2016-12-05 at 17 26 59" src="https://cloud.githubusercontent.com/assets/2266310/20892848/1011927a-bb10-11e6-9409-858528ffea20.png">

Although we expect to have something like that:
<img width="241" alt="screen shot 2016-12-05 at 17 27 29" src="https://cloud.githubusercontent.com/assets/2266310/20892872/1e9146ce-bb10-11e6-8466-82b6ab0b2048.png">

Please let me know if there are not enough details about this matter.
Kind regards,
Dmitrijs.

**Comment by colinmeinke** [comment]
@dmitrijs-balcers I'm not sure your issue has anything to do with this library. http://codepen.io/colinmeinke/pen/VmXRQY – this pen shows two paths created both with and without being put through cubify.

**Comment by dmitrijs-balcers** [comment]
@colinmeinke Thank you, looks like I wrongly converted path with arc to points. I think `svg-points` will do the job.
