### ISSUE TITLE
Question: is now moveIndex applies to polyline?

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/points#12]
Hi. Thanks for amazing and best library for making our job easier. As i know polyline aka non closed, non joined shape cannot be change index. It is now possible?

Last commit sometimes may get wrong shape looking for me, but i not sure.

**Comment by colinmeinke** [comment]
Yes! Since [2.0.0](https://github.com/colinmeinke/points/releases/tag/v2.0.0). Check out https://github.com/colinmeinke/points/blob/master/test/moveIndex.js#L139L153

**Comment by dalisoft** [comment]
very nice. thanks

**Comment by dalisoft** [comment]
@colinmeinke 
i see it not works. pls test, http://codepen.io/dalisoft/pen/xgOeBK
remove moveindex to see original shape.

**Comment by dalisoft** [comment]
@colinmeinke any news about this?

**Comment by colinmeinke** [comment]
I'm working on it, should be fixed today.

**Comment by dalisoft** [comment]
Thanks

**Comment by dalisoft** [comment]
I think `moveIndex` for non-closed shapes are not possible

**Comment by colinmeinke** [comment]
@dalisoft fixed with latest releases of points and svg-points

**Comment by dalisoft** [comment]
Thanks

**Comment by dalisoft** [comment]
@colinmeinke Please test my pen with some little demo: http://codepen.io/dalisoft/pen/xgOeBK
for me looks like buggy, i don't think it buggy or no. but nice tools and i feel performance gain after release

**Comment by colinmeinke** [comment]
looks good

**Comment by dalisoft** [comment]
it circles the shape
