### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rubybrowncoat** [colinmeinke/points#26]
```
/node_modules/points/cjs/decurve.js:80
var straighten = function straighten(prevPoint, point, accuracy) {
                                    ^

RangeError: Maximum call stack size exceeded
    at straighten (/node_modules/points/cjs/decurve.js:80:37)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
    at straighten (node_modules/points/cjs/decurve.js:101:39)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
    at straighten (/node_modules/points/cjs/decurve.js:101:39)
```

Using svg-points to make the points array and then using either position or length triggers this error on several different paths. Any ideas what I might be doing wrong?

Providing a couple for example but I've got plenty:
`M3337.1,5965.8c-26.4-9.2-64.5-15.1-87,4.6c3.7,0.8,7.5,1.9,11.1,3.3c2.9,1.1,4.7,4.3,4.4,8.2c-0.3,5-3.6,8.4-7.8,7.6c-3.3-0.6-6.4-1.9-9.7-2.4c-4.6-0.6-9.9,3.1-11.8,7.7c-2.1,5.3-0.5,12.5,3.8,16c3.5,2.8,7.8,3.4,11.8,1.8c3-1.2,6.2-2.9,8.3-5.2c3.9-4.3,7.9-5.5,13.3-3.1c5.2,2.4,9.4,0.3,13.8-2.9c7.6-5.5,9-5,10.7,4.5c1.5,8.3,3.9,16.2,7.7,23.7c0.6,1.1,2.6,1.6,4,2c0.4,0.1,1.6-0.9,1.7-1.6c1.6-10.7,2.9-21.4-0.7-32.1c-2.1-6.3-4-12.7-5.6-19.1c-0.3-1.1,1.2-2.7,2.1-3.8c0.4-0.5,1.7-0.6,2.4-0.3c3.8,1.6,7.7,3.3,11.3,5.3c4.1,2.3,4.4,6,1.3,10.3c-4.1,5.7-4.1,5.7,1.7,11.8l-0.1-0.1c-2.5,5.4-4.2,10.7-3.4,16.9c1.3,9.9,1.9,19.9,3.1,29.8c0.4,3.2,1.6,6.4,3.1,9.3c0.5,1,2.9,1.8,4.2,1.6c1.3-0.2,3.1-1.8,3.3-2.9c0.6-5,0.7-10,0.7-15c0-5.3,1.5-9.7,5.9-13c2.6-2,5-4.4,7.3-6.8c2.7-2.9,3.4-8.2,0.7-11.6c-4.7-6.2-7.8-12.8-7.3-20.7c0.1-0.8,0.5-2,1-2.2c1.5-0.4,3.8-1.1,4.5-0.4c7,7.1,13.8,14.4,20.3,21.9c2.1,2.4,3.7,5.4,4.8,8.4C3379.6,5993.2,3357.7,5972,3337.1,5965.8zM3258.8,6027.3c1-2.2,1.4-5.7,3.1-6.4c7.4-3.2,14.5-7.4,22.7-8.4c2.7-0.3,6.4,4.1,5.6,6.7c-2.3,7.4-7.7,11.4-14.5,10.6C3270,6029.1,3264.4,6028.1,3258.8,6027.3C3258.7,6027.2,3258.8,6027.3,3258.8,6027.3zM3349.6,6039.3c0.1,2.8-1,4.6-3.4,5.5c-3.1,1.2-6.6-1.3-6.2-4.6c0.3-2.7,2.1-4.1,4.6-4.5C3347,6035.4,3349.3,6037.2,3349.6,6039.3z`

`M5053.6,5247.3c2.5,0.6,7.5,1.3,8.1,0.6c3.1-13.2-2.5-26.3-4.4-39.5c-2.5-13.8-5-27.6-1.3-41.4c3.6-14,7.9-28.2,8.8-42.6c0,0,0,0,0,0c-9.8-2.6-19-7.1-27.4-12.9c0.9,5.6,1.1,11.2,0.4,16.7c-1.3,8.4-7.2,12.9-14.7,14.5c-2.1,11.3-5.4,22.5-4.1,34.4c1.9,20.1,0.6,39.5,1.3,59.6c-1.4,0.2-2.7,0.5-4.1,0.8c2.9,1.5,5.9,2.6,9.1,3C5035.4,5242.3,5044.2,5243.6,5053.6,5247.3z`

`M4247.5,5519.1c-14.6,0-30.7-8.7-44.6-2.8c-8.8,3.8-10,19.4-20.1,23.8c-5.9,2.7-11.9-1.1-17.4-3.8c-8.4,11.8-16.9,23.4-24.6,36.4c-1.9,3.1-5,6.9-7.5,10.7c-1.3,1.6-2.4,3.6-3.4,5.7c0.1,0,0.2-0.1,0.3-0.1c2.3,11.6,14.5,24.2,15.2,35c21.9-5.5,43.8-11.3,65.6-17.5c0,0,0,0,0,0.1c6.7-17.8,12.8-35.5,21.9-52.1C4239,5542.9,4243,5530.9,4247.5,5519.1z`

**Comment by colinmeinke** [comment]
@rubybrowncoat could you create a complete example as a codepen please so I can take a look?

**Comment by Webbmekanikern** [comment]
I can confirm this issue. The `straighten()` function is "too recursive" and is killing the call stack. It needs something that pauses the execution, like a `Promise` or the `setImmediate()` function.

**Comment by colinmeinke** [comment]
@rubybrowncoat @Webbmekanikern thanks, I've reproduced here https://codepen.io/colinmeinke/pen/XLPQVo, I'll look into making sure this doesn't recur infinitely.

**Comment by colinmeinke** [comment]
Having looked into this further, it occurs when the decurve function tries to straighten a curve between two points where the x and y values are identical. I'm pushing a fix for this now.
