### ISSUE TITLE
ISSUE: Decurve Function not work

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/points#9]
Hi @colinmeinke, decurve function causes maxium call excedded, below i have log (maybe helps you).
I changed code place/structure for my own work, but what function caused i have

```
[LOGGY.JS, pre-build]: executed via [decurve(shape, [[arguments]]) >> straight]
[{
	Browser: Chrome,
	Version: 52.1,
	Task Manager: [{title:'undefined',path:'file:///D:/Apps/points.js/compiled/points.html'}]
	OS: Windows7,
	Machine: Intel,
	GPU: Intel,
	CPU Usage: [{amount:69,unit:'%'}, {count:2,used:2}],
	Memory Usage: [{amount:57,unit:'%'}, {total:3221225472,used:1836098519}],
	Model: "Acer 5610z",
	Manf: "Acer, Inc."
},loggyjs:!0,date:[[22, 30], [17,10,2016]]]

points.js:1222 Uncaught RangeError: Maximum call stack size exceeded
>> straight @ points.js:1222
>> straighten @ points.js:1239
>> straighten @ points.js:1250
>> straighten @ points.js:1250
>> straighten @ points.js:1250
>> straighten @ points.js:1250
>> straighten @ points.js:1250
>> straighten @ points.js:1250
>> straighten @ points.js:1250
>> straighten @ points.js:1250
>> angleFromSides:NaN @ points.js:1250
```

**Comment by colinmeinke** [comment]
Could you post the code that caused this?

**Comment by dalisoft** [comment]
I can't post there, because i'm very hard worked to get it work. Also improved some bugs and improvements did.
So, can you give me e-mail to send code?

**Comment by colinmeinke** [comment]
Is this an issue with Points, or your own library? Decurve is not part of Points' public API. It should only be accessed indirectly through one of the public functions, such as `boundingBox`.

```js
import { boundingBox } from 'points'
const yourShape = {...}
boundingBox(yourShape)
```

Please can you let me know your exact values of `a` and `ai.decurve` that cause decurve to throw an error, so I can recreate.

**Comment by dalisoft** [comment]
It's issue with Points.js, `ai.decurve = 1` and
`a = {x:525.667,y:321.333,moveTo:true} {x:462.8335,y:321.333} {x:400,y:321.333} {x:274.333,y:321.333} {x:274.333,y:200} {x:274.333,y:78.667} {x:399.9995,y:78.667} {x:525.666,y:78.667} {x:525.666,y:200} {x:525.666,y:321.333} {x:525.6665,y:321.333} {x:525.667,y:321.333}`

**Comment by colinmeinke** [comment]
As the test proves, this is not an issue with points. It must be something you have changed within your library.

**Comment by dalisoft** [comment]
It worked without issues?
I am tested with many cases. Not worked. I can conect to you with some way?

**Comment by colinmeinke** [comment]
The `decurve` function will just return the input shape if the shape does not have any curves (which your example does not). There is no reason `decurve` should be iterating over the points and removing the curves (which it is because `angleFromSides` is being called). Are you using Points as it is provided, or have you modified the `decurve` function?

You can test that it works on your machine by cloning this repo and then running:

```
npm install
npm test
```

**Comment by dalisoft** [comment]
I have original Points.js decurve function. Decurve increases the points number, like from 12 to 30 or 40?

**Comment by colinmeinke** [comment]
That is the functionality of `add` https://github.com/colinmeinke/points#add

As I said, `decurve` isn't part of the public API, so shouldn't be used.

**Comment by dalisoft** [comment]
Ok. Thanks
